#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# must be executed from ..../processmaker/tests/functional/src/main
# must include selenium libs and junit in resources folder
#compile common
javac -cp .:./resources/libs/*:./resources/selenium-java-2.25.0.jar ./java/com/colosa/qa/automatization/common/*.java

#compile pages
javac -cp .:./resources/libs/*:./resources/selenium-java-2.25.0.jar:./java/:./resources/junit-4.8.2.jar ./java/com/colosa/qa/automatization/pages/*.java

#compile tests
javac -cp .:./resources/libs/*:./resources/selenium-java-2.25.0.jar:./java/:./resources/junit-4.8.2.jar ./java/com/colosa/qa/automatization/tests/login/*.java
