#!/bin/bash
# must be executed from ..../processmaker/tests/functional/src/main
# must include selenium libs and junit in resources folder
#Run TestLogin
java -cp .:./resources/libs/*:./resources/selenium-java-2.25.0.jar:./java/:./resources/junit-4.8.2.jar org.junit.runner.JUnitCore com.colosa.qa.automatization.tests.login.TestLogin